runtime: php55
api_version: 1
threadsafe: true

handlers:  
- url: /Ctct
  script: /Ctct/index.html

- url: /Ctct/
  script: /Ctct/index.html

#- url: /Ctct/(.+\.(html|php|json|lock|ini))$
#  script: \1

#- url: /Ctct/css/(.+\.(css))$
#  script: \1
  
- url: /get
  script: /get.php

- url: /get\.php
  script: /get.php

- url: /getcc
  script: /Ctct/getcc.php

- url: /(getcc\.php)
  script: /Ctct/getcc.php

- url: /getprofile\.php
  script: static/getprofile.php

- url: /getprofile
  script: /static/getprofile.php

- url: /ymapi
  script: /static/ymapi.php

- url: /ymapi\.php
  script: static/ymapi.php

- url: /bills
  script: /static/example2.html

- url: /static/kliss/
  script: /static/example2.html

- url: /(.+\.(html|php|json|lock|ini|kml|txt))$
  script: \1

#- url: /static/kliss/(.+\.(html|php|json|lock|ini|kml|txt))$
#  script: \1

- url: /static/(.+\.(html|php|json|lock|ini|kml|txt))$
  script: \1

- url: /(.+\.(gif|png|jpg|php|xml|kml|json))$
  upload: static/.+\.(gif|png|jpg|xml|kml|json)$
  static_files: static/
  http_headers:
    Access-Control-Allow-Origin: '*' #'https://site-ksbar.c9users.io'
    
#- url: /static/kliss
#  static_dir: /static/kliss
#  http_headers:
#    Access-Control-Allow-Origin: '*' #'https://site-ksbar.c9users.io'

  
# https://gist.github.com/darktable/873098/beddaa449e41954bfb1e86a85f1d8b699cf76a42
- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: static/\1
  upload: static/(.*\.(appcache|manifest))

- url: /(.*\.atom)
  mime_type: application/atom+xml
  static_files: static/\1
  upload: static/(.*\.atom)

- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  static_files: static/\1
  upload: static/(.*\.crx)

- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: /Ctct/css/(.*\.css)

- url: /(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  static_files: /static/\1
  upload: /static/(.*\.eot)

- url: /(.*\.htc)
  mime_type: text/x-component
  static_files: /static/\1
  upload: /static/(.*\.htc)

- url: /(.*\.html)
  mime_type: text/html
  static_files: /static/\1
  upload: /static/(.*\.html)

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: static/\1
  upload: static/(.*\.ico)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: static/\1
  upload: static/(.*\.json)
  http_headers: 
    Access-Control-Allow-Origin: '*'

- url: /(.*\.m4v)
  mime_type: video/m4v
  static_files: static/\1
  upload: static/(.*\.m4v)

- url: /(.*\.mp4)
  mime_type: video/mp4
  static_files: static/\1
  upload: static/(.*\.mp4)

- url: /(.*\.(ogg|oga))
  mime_type: audio/ogg
  static_files: static/\1
  upload: static/(.*\.(ogg|oga))

- url: /(.*\.ogv)
  mime_type: video/ogg
  static_files: static/\1
  upload: static/(.*\.ogv)

- url: /(.*\.otf)
  mime_type: font/opentype
  static_files: static/\1
  upload: static/(.*\.otf)

- url: /(.*\.rss)
  mime_type: application/rss+xml
  static_files: static/\1
  upload: static/(.*\.rss)

- url: /(.*\.safariextz)
  mime_type: application/octet-stream
  static_files: static/\1
  upload: static/(.*\.safariextz)

- url: /(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: static/\1
  upload: static/(.*\.(svg|svgz))

- url: /(.*\.swf)
  mime_type: application/x-shockwave-flash
  static_files: static/\1
  upload: static/(.*\.swf)

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: static/\1
  upload: static/(.*\.ttf)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /(.*\.unity3d)
  mime_type: application/vnd.unity
  static_files: static/\1
  upload: static/(.*\.unity3d)

- url: /(.*\.webm)
  mime_type: video/webm
  static_files: static/\1
  upload: static/(.*\.webm)

- url: /(.*\.webp)
  mime_type: image/webp
  static_files: static/\1
  upload: static/(.*\.webp)

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: static/\1
  upload: static/(.*\.woff)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: static/\1
  upload: static/(.*\.xml)

- url: /(.*\.kml)
  mime_type: application/vnd.google-earth.kml+xml
  static_files: /static/\1
  upload: /static/(.*\.kml)
# application/vnd.google-earth.kml+xml
# application/vnd.google-earth.kmz

- url: /(.*\.xpi)
  mime_type: application/x-xpinstall
  static_files: static/\1
  upload: static/(.*\.xpi)

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /favicon\.png
  static_files: favicon.png
  upload: favicon\.png

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: static/\1
  upload: static/(.*\.(mid|midi|mp3|wav))  

# windows files
- url: /(.*\.(doc|exe|ppt|rtf|xls))
  static_files: static/\1
  upload: static/(.*\.(doc|exe|ppt|rtf|xls))

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: static/\1
  upload: static/(.*\.(bz2|gz|rar|tar|tgz|zip))

# index files
# - url: /(.*)/
#  static_files: static/\1/index.html
#  upload: static/(.*)/index.html

# index files
- url: /(.+\.(html|php|json|lock|ini|md|ico|kml|txt))$
  script: \1

- url: /.*
  script: /index.php
